//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compta.Ledger.Core.orgTestapp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compta.Ledger.Core.orgTestapp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.Root.
        /// </summary>
        public static string Add_Root {
            get {
                return ResourceManager.GetString("Add.Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.Loading.
        /// </summary>
        public static string Grid_Loading {
            get {
                return ResourceManager.GetString("Grid.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.Search.categories.
        /// </summary>
        public static string Input_Search_categories {
            get {
                return ResourceManager.GetString("Input.Search.categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.Exception.
        /// </summary>
        public static string Move_Exception {
            get {
                return ResourceManager.GetString("Move.Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.AddChildTo.
        /// </summary>
        public static string Node_AddChildTo {
            get {
                return ResourceManager.GetString("Node.AddChildTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.AddRoot.
        /// </summary>
        public static string Node_AddRoot {
            get {
                return ResourceManager.GetString("Node.AddRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.AndAllItsChildren.
        /// </summary>
        public static string Node_AndAllItsChildren {
            get {
                return ResourceManager.GetString("Node.AndAllItsChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.DeleteException.
        /// </summary>
        public static string Node_DeleteException {
            get {
                return ResourceManager.GetString("Node.DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.EntreCategory.
        /// </summary>
        public static string Node_EntreCategory {
            get {
                return ResourceManager.GetString("Node.EntreCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.GetAllException.
        /// </summary>
        public static string Node_GetAllException {
            get {
                return ResourceManager.GetString("Node.GetAllException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.GetbyIdException.
        /// </summary>
        public static string Node_GetbyIdException {
            get {
                return ResourceManager.GetString("Node.GetbyIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.GetChildrenException.
        /// </summary>
        public static string Node_GetChildrenException {
            get {
                return ResourceManager.GetString("Node.GetChildrenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.MoveException.
        /// </summary>
        public static string Node_MoveException {
            get {
                return ResourceManager.GetString("Node.MoveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.MoveToDescendant.Description.
        /// </summary>
        public static string Node_MoveToDescendant_Description {
            get {
                return ResourceManager.GetString("Node.MoveToDescendant.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.MoveToDescendant.Title.
        /// </summary>
        public static string Node_MoveToDescendant_Title {
            get {
                return ResourceManager.GetString("Node.MoveToDescendant.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.NotFound.
        /// </summary>
        public static string Node_NotFound {
            get {
                return ResourceManager.GetString("Node.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.NotFound.Description.
        /// </summary>
        public static string Node_NotFound_Description {
            get {
                return ResourceManager.GetString("Node.NotFound.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.NotFound.Title.
        /// </summary>
        public static string Node_NotFound_Title {
            get {
                return ResourceManager.GetString("Node.NotFound.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.Rename.Description.
        /// </summary>
        public static string Node_Rename_Description {
            get {
                return ResourceManager.GetString("Node.Rename.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.Rename.Title.
        /// </summary>
        public static string Node_Rename_Title {
            get {
                return ResourceManager.GetString("Node.Rename.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.RenameException.
        /// </summary>
        public static string Node_RenameException {
            get {
                return ResourceManager.GetString("Node.RenameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.Required.
        /// </summary>
        public static string Node_Required {
            get {
                return ResourceManager.GetString("Node_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.Update.Description.
        /// </summary>
        public static string Node_Update_Description {
            get {
                return ResourceManager.GetString("Node.Update.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.Update.Title.
        /// </summary>
        public static string Node_Update_Title {
            get {
                return ResourceManager.GetString("Node.Update.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.Create.
        /// </summary>
        public static string Root_Create {
            get {
                return ResourceManager.GetString("Root.Create", resourceCulture);
            }
        }
    }
}
